INSERT INTO departments(name) values ('Engineering');
INSERT INTO departments(name) values ('Marketing');
INSERT INTO departments(name) values ('IT');
INSERT INTO departments(name) values ('HR');
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('Luna', 'Tyler', 'Female',  2, 'luna.tyler@observepoint.com', 'Analyst', '1985-09-01' );
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('Chris', 'Joe', 'Male', 1, 'chris.joe@observepoint.com', 'Manager', '1970-11-01' );
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('Jess', 'Jo', 'Non-Binary', 3, 'jess.jo@observepoint.com', 'Software Engineer', '1989-12-11');
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('Tom', 'Hardy', 'Male',  3, 'tom.hardy@observepoint.com', 'Director', '1995-04-01' );
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('Jane', 'Doe', 'Female', 4, 'jane.doe@observepoint.com', 'Manager', '1970-04-01' );
INSERT INTO employees(first_name, last_name, gender, dept_id, email_id, job_title, date_of_birth) values ('John', 'Abe', 'Male', 3, 'john.abe@observepoint.com', 'Software Engineer', '1989-08-11');
INSERT INTO jobs(job_title) values ('Associate Software Engineer');
INSERT INTO jobs(job_title) values ('Senior Software Engineer');
INSERT INTO jobs(job_title) values ('Analyst');
INSERT INTO jobs(job_title) values ('Consultant');
INSERT INTO jobs(job_title) values ('Director');
INSERT INTO jobs(job_title) values ('Manager');